package br.edu.unipampa.model;
// Generated 12/06/2014 22:07:01 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Aluno generated by hbm2java
 */
public class Aluno  implements java.io.Serializable {


     private int matricula;
     private Pessoa pessoa;
     private Integer cargaHoraria;
     private Set bancas = new HashSet(0);
     private Set temas = new HashSet(0);

    public Aluno() {
    }

	
    public Aluno(int matricula, Pessoa pessoa) {
        this.matricula = matricula;
        this.pessoa = pessoa;
    }
    public Aluno(int matricula, Pessoa pessoa, Integer cargaHoraria, Set bancas, Set temas) {
       this.matricula = matricula;
       this.pessoa = pessoa;
       this.cargaHoraria = cargaHoraria;
       this.bancas = bancas;
       this.temas = temas;
    }
   
    public int getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Integer getCargaHoraria() {
        return this.cargaHoraria;
    }
    
    public void setCargaHoraria(Integer cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }
    public Set getBancas() {
        return this.bancas;
    }
    
    public void setBancas(Set bancas) {
        this.bancas = bancas;
    }
    public Set getTemas() {
        return this.temas;
    }
    
    public void setTemas(Set temas) {
        this.temas = temas;
    }

    public String getSenha(){
        return pessoa.getSenha();
    }

    public String getUsuario(){
        return pessoa.getUsuario();
    }


}


