package br.edu.unipampa.model;
// Generated 16/07/2014 21:01:23 by Hibernate Tools 3.6.0

import br.edu.unipampa.model.web.AcessoSistema;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Aluno generated by hbm2java
 */
public class Aluno extends Pessoa implements java.io.Serializable {

    private int matricula;
    private Pessoa pessoa;
    private Integer cargaHoraria;
    private Set bancas = new HashSet(0);
    private Set temas = new HashSet(0);

    public Aluno() {
    }

    public Aluno(int matricula, Pessoa pessoa) {
        this.matricula = matricula;
        this.pessoa = pessoa;
    }

    public Aluno(int matricula, Pessoa pessoa, Integer cargaHoraria, Set bancas, Set temas) {
        this.matricula = matricula;
        this.pessoa = pessoa;
        this.cargaHoraria = cargaHoraria;
        this.bancas = bancas;
        this.temas = temas;
    }

    public int getMatricula() {
        return this.matricula;
    }

    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }

    public Pessoa getPessoa() {
        return this.pessoa;
    }

    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    public Integer getCargaHoraria() {
        return this.cargaHoraria;
    }

    public void setCargaHoraria(Integer cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }

    public Set getBancas() {
        return this.bancas;
    }

    public void setBancas(Set bancas) {
        this.bancas = bancas;
    }

    public Set getTemas() {
        return this.temas;
    }

    public void setTemas(Set temas) {
        this.temas = temas;
    }

    public String getSenha() {
        return pessoa.getSenha();
    }

    public String getNome() {
        return pessoa.getNome();
    }

    public String getUsuario() {
        return pessoa.getUsuario();
    }

    public boolean cadastrarTema(int matriculaAluno, String usuarioProfessor, String descricaoTema) {
        List<Orientador> OrientadoresEncontrados;
        List<Aluno> alunosEncontrados;
        Aluno aluno = null;
        Orientador orientador = null;
        Tema tema = new Tema();
        AcessoSistema acessoSistema = new AcessoSistema();

        OrientadoresEncontrados = acessoSistema.procurarListaOrientadores();
        alunosEncontrados = acessoSistema.procurarListaAlunos();

        if (OrientadoresEncontrados != null || alunosEncontrados != null) {
            for (Aluno alunoEncontrado : alunosEncontrados) {
                if (alunoEncontrado.getMatricula() == matriculaAluno) {
                    aluno = alunoEncontrado;
                    break;
                }
            }

            for (Orientador orientadorEncontrado : OrientadoresEncontrados) {
                if (orientadorEncontrado.getUsuario().equals(usuarioProfessor)) {
                    orientador = orientadorEncontrado;
                }
            }

            tema.setAluno(aluno);
            tema.setOrientador(orientador);
            tema.setAprovado(Tema.NAO_APROVADO);
            tema.setDescricao(descricaoTema);

            return acessoSistema.cadastrarTema(tema);
        }
        return false;
    }

}
