package br.edu.unipampa.model;
// Generated 12/06/2014 22:07:01 by Hibernate Tools 3.6.0



/**
 * Banca generated by hbm2java
 */
public class Banca  implements java.io.Serializable {


     private Integer idBanca;
     private Professor professor;
     private Pessoaexterna pessoaexterna;
     private Aluno aluno;
     private String local;
     private String horario;
     private String data;

    public Banca() {
    }

	
    public Banca(Professor professor, Pessoaexterna pessoaexterna, Aluno aluno) {
        this.professor = professor;
        this.pessoaexterna = pessoaexterna;
        this.aluno = aluno;
    }
    public Banca(Professor professor, Pessoaexterna pessoaexterna, Aluno aluno, String local, String horario, String data) {
       this.professor = professor;
       this.pessoaexterna = pessoaexterna;
       this.aluno = aluno;
       this.local = local;
       this.horario = horario;
       this.data = data;
    }
   
    public Integer getIdBanca() {
        return this.idBanca;
    }
    
    public void setIdBanca(Integer idBanca) {
        this.idBanca = idBanca;
    }
    public Professor getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Professor professor) {
        this.professor = professor;
    }
    public Pessoaexterna getPessoaexterna() {
        return this.pessoaexterna;
    }
    
    public void setPessoaexterna(Pessoaexterna pessoaexterna) {
        this.pessoaexterna = pessoaexterna;
    }
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }




}


