package br.edu.unipampa.model;
// Generated 02/07/2014 01:11:04 by Hibernate Tools 3.6.0



/**
 * Banca generated by hbm2java
 */
public class Banca  implements java.io.Serializable {


     private Integer idBanca;
     private Pessoa pessoaByConvidado3IdPessoa;
     private Professor professor;
     private Pessoa pessoaByConvidado1IdPessoa;
     private Pessoa pessoaByConvidado2IdPessoa;
     private Aluno aluno;
     private String data;
     private String horario;
     private String local;

    public Banca() {
    }

	
    public Banca(Professor professor, Pessoa pessoaByConvidado1IdPessoa, Pessoa pessoaByConvidado2IdPessoa, Aluno aluno) {
        this.professor = professor;
        this.pessoaByConvidado1IdPessoa = pessoaByConvidado1IdPessoa;
        this.pessoaByConvidado2IdPessoa = pessoaByConvidado2IdPessoa;
        this.aluno = aluno;
    }
    public Banca(Pessoa pessoaByConvidado3IdPessoa, Professor professor, Pessoa pessoaByConvidado1IdPessoa, Pessoa pessoaByConvidado2IdPessoa, Aluno aluno, String data, String horario, String local) {
       this.pessoaByConvidado3IdPessoa = pessoaByConvidado3IdPessoa;
       this.professor = professor;
       this.pessoaByConvidado1IdPessoa = pessoaByConvidado1IdPessoa;
       this.pessoaByConvidado2IdPessoa = pessoaByConvidado2IdPessoa;
       this.aluno = aluno;
       this.data = data;
       this.horario = horario;
       this.local = local;
    }
   
    public Integer getIdBanca() {
        return this.idBanca;
    }
    
    public void setIdBanca(Integer idBanca) {
        this.idBanca = idBanca;
    }
    public Pessoa getPessoaByConvidado3IdPessoa() {
        return this.pessoaByConvidado3IdPessoa;
    }
    
    public void setPessoaByConvidado3IdPessoa(Pessoa pessoaByConvidado3IdPessoa) {
        this.pessoaByConvidado3IdPessoa = pessoaByConvidado3IdPessoa;
    }
    public Professor getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Professor professor) {
        this.professor = professor;
    }
    public Pessoa getPessoaByConvidado1IdPessoa() {
        return this.pessoaByConvidado1IdPessoa;
    }
    
    public void setPessoaByConvidado1IdPessoa(Pessoa pessoaByConvidado1IdPessoa) {
        this.pessoaByConvidado1IdPessoa = pessoaByConvidado1IdPessoa;
    }
    public Pessoa getPessoaByConvidado2IdPessoa() {
        return this.pessoaByConvidado2IdPessoa;
    }
    
    public void setPessoaByConvidado2IdPessoa(Pessoa pessoaByConvidado2IdPessoa) {
        this.pessoaByConvidado2IdPessoa = pessoaByConvidado2IdPessoa;
    }
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }




}


