package br.edu.unipampa.model;
// Generated 16/07/2014 21:01:23 by Hibernate Tools 3.6.0

import br.edu.unipampa.model.web.AcessoSistema;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa implements java.io.Serializable {

    private Integer idPessoa;
    private String usuario;
    private String senha;
    private String email;
    private String nome;
    private Integer areaAtuacao;
    private Set bancasForConvidado2IdPessoa = new HashSet(0);
    private Set bancasForConvidado1IdPessoa = new HashSet(0);
    private Set alunos = new HashSet(0);
    private Set professors = new HashSet(0);
    private Set tecnicoadministrativos = new HashSet(0);
    private Set bancasForConvidado3IdPessoa = new HashSet(0);
    private Set pessoaexternas = new HashSet(0);

    public Pessoa() {
    }

    public Pessoa(String usuario, String senha, String email) {
        this.usuario = usuario;
        this.senha = senha;
        this.email = email;
    }

    public Pessoa(String usuario, String senha, String email, String nome, Integer areaAtuacao, Set bancasForConvidado2IdPessoa, Set bancasForConvidado1IdPessoa, Set alunos, Set professors, Set tecnicoadministrativos, Set bancasForConvidado3IdPessoa, Set pessoaexternas) {
        this.usuario = usuario;
        this.senha = senha;
        this.email = email;
        this.nome = nome;
        this.areaAtuacao = areaAtuacao;
        this.bancasForConvidado2IdPessoa = bancasForConvidado2IdPessoa;
        this.bancasForConvidado1IdPessoa = bancasForConvidado1IdPessoa;
        this.alunos = alunos;
        this.professors = professors;
        this.tecnicoadministrativos = tecnicoadministrativos;
        this.bancasForConvidado3IdPessoa = bancasForConvidado3IdPessoa;
        this.pessoaexternas = pessoaexternas;
    }

    public Integer getIdPessoa() {
        return this.idPessoa;
    }

    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }

    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Integer getAreaAtuacao() {
        return this.areaAtuacao;
    }

    public void setAreaAtuacao(Integer areaAtuacao) {
        this.areaAtuacao = areaAtuacao;
    }

    public Set getBancasForConvidado2IdPessoa() {
        return this.bancasForConvidado2IdPessoa;
    }

    public void setBancasForConvidado2IdPessoa(Set bancasForConvidado2IdPessoa) {
        this.bancasForConvidado2IdPessoa = bancasForConvidado2IdPessoa;
    }

    public Set getBancasForConvidado1IdPessoa() {
        return this.bancasForConvidado1IdPessoa;
    }

    public void setBancasForConvidado1IdPessoa(Set bancasForConvidado1IdPessoa) {
        this.bancasForConvidado1IdPessoa = bancasForConvidado1IdPessoa;
    }

    public Set getAlunos() {
        return this.alunos;
    }

    public void setAlunos(Set alunos) {
        this.alunos = alunos;
    }

    public Set getProfessors() {
        return this.professors;
    }

    public void setProfessors(Set professors) {
        this.professors = professors;
    }

    public Set getTecnicoadministrativos() {
        return this.tecnicoadministrativos;
    }

    public void setTecnicoadministrativos(Set tecnicoadministrativos) {
        this.tecnicoadministrativos = tecnicoadministrativos;
    }

    public Set getBancasForConvidado3IdPessoa() {
        return this.bancasForConvidado3IdPessoa;
    }

    public void setBancasForConvidado3IdPessoa(Set bancasForConvidado3IdPessoa) {
        this.bancasForConvidado3IdPessoa = bancasForConvidado3IdPessoa;
    }

    public Set getPessoaexternas() {
        return this.pessoaexternas;
    }

    public void setPessoaexternas(Set pessoaexternas) {
        this.pessoaexternas = pessoaexternas;
    }

    /**
     * Salva a nota que este avalidor deu para o aluno
     *
     * @param notaFinal nota para se salvar
     * @param banca banca que esse avaliador está presente
     */
    public void avaliarAluno(float notaFinal, Banca banca) {
        AcessoSistema acessoSistema = new AcessoSistema();
        Tema tema = acessoSistema.procurarTema(banca.getAluno());
        List<Tcc> tccEncontrados = acessoSistema.procurarTCC(banca.getAluno().getMatricula());

        //Não esquecer de depois lidar com mais de um Tcc
        for (Tcc tcc : tccEncontrados) {
            Integer idOrientador = banca.getOrientadorByOrientadorIdOrientador().getIdPessoa();
            Integer idConvidado1 = banca.getPessoaByConvidado1IdPessoa().getIdPessoa();
            Integer idConvidado2 = banca.getPessoaByConvidado2IdPessoa().getIdPessoa();
            if (banca.getOrientadorByCoorientadorIdOrientador() != null
                    && getIdPessoa() == banca.getOrientadorByCoorientadorIdOrientador().getIdPessoa()) {
                tcc.setNotaCoorientador(notaFinal);
            } else if (getIdPessoa() == banca.getOrientadorByOrientadorIdOrientador().getIdPessoa()) {
                tcc.setNotaOrientador(notaFinal);
            } else if (getIdPessoa() == banca.getPessoaByConvidado1IdPessoa().getIdPessoa()) {
                tcc.setNotaConvidado1(notaFinal);
            } else if (getIdPessoa() == banca.getPessoaByConvidado2IdPessoa().getIdPessoa()) {
                tcc.setNotaConvidado2(notaFinal);
            }
            if (banca.getPessoaByConvidado3IdPessoa() == null) {
                if (tcc.getNotaOrientador() != -1
                        && tcc.getNotaConvidado1() != -1
                        && tcc.getNotaConvidado2() != -1) {
                    tcc.setStatus(2);
                }
            }else{
                if (tcc.getNotaOrientador() != -1
                        && tcc.getNotaConvidado1() != -1
                        && tcc.getNotaConvidado2() != -1
                        && tcc.getNotaCoorientador() != -1) {
                    tcc.setStatus(2);
                }
            }
            acessoSistema.atualizarTcc(tcc);
        }

    }

}
