package br.edu.unipampa.model;
// Generated 16/07/2014 21:01:23 by Hibernate Tools 3.6.0



/**
 * Pessoaexterna generated by hbm2java
 */
public class Pessoaexterna extends Pessoa implements java.io.Serializable {


     private int idPessoaExterna;
     private Pessoa pessoa;
     private String cpf;
     private String instituicao;
     private Integer nivelFormacao;

    public Pessoaexterna() {
    }

	
    public Pessoaexterna(int idPessoaExterna, Pessoa pessoa) {
        this.idPessoaExterna = idPessoaExterna;
        this.pessoa = pessoa;
    }
    public Pessoaexterna(int idPessoaExterna, Pessoa pessoa, String cpf, String instituicao, Integer nivelFormacao) {
       this.idPessoaExterna = idPessoaExterna;
       this.pessoa = pessoa;
       this.cpf = cpf;
       this.instituicao = instituicao;
       this.nivelFormacao = nivelFormacao;
    }
   
    public int getIdPessoaExterna() {
        return this.idPessoaExterna;
    }
    
    public void setIdPessoaExterna(int idPessoaExterna) {
        this.idPessoaExterna = idPessoaExterna;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getInstituicao() {
        return this.instituicao;
    }
    
    public void setInstituicao(String instituicao) {
        this.instituicao = instituicao;
    }
    public Integer getNivelFormacao() {
        return this.nivelFormacao;
    }
    
    public void setNivelFormacao(Integer nivelFormacao) {
        this.nivelFormacao = nivelFormacao;
    }

    @Override
    public String getSenha() {
        return pessoa.getSenha();
    }

    @Override
    public String getNome() {
        return pessoa.getNome();
    }

    @Override
    public String getUsuario() {
        return pessoa.getUsuario();
    }
    
    @Override
    public String getEmail() {
        return pessoa.getEmail();
    }
    
    @Override
    public Integer getIdPessoa() {
        return pessoa.getIdPessoa();
    }

}


