package br.edu.unipampa.model;
// Generated 12/06/2014 22:07:01 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private Integer idPessoa;
     private String email;
     private String usuario;
     private String senha;
     private Set professors = new HashSet(0);
     private Set alunos = new HashSet(0);
     private Set pessoaexternas = new HashSet(0);

    public Pessoa() {
    }

	
    public Pessoa(String email, String usuario, String senha) {
        this.email = email;
        this.usuario = usuario;
        this.senha = senha;
    }
    public Pessoa(String email, String usuario, String senha, Set professors, Set alunos, Set pessoaexternas) {
       this.email = email;
       this.usuario = usuario;
       this.senha = senha;
       this.professors = professors;
       this.alunos = alunos;
       this.pessoaexternas = pessoaexternas;
    }
   
    public Integer getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set getProfessors() {
        return this.professors;
    }
    
    public void setProfessors(Set professors) {
        this.professors = professors;
    }
    public Set getAlunos() {
        return this.alunos;
    }
    
    public void setAlunos(Set alunos) {
        this.alunos = alunos;
    }
    public Set getPessoaexternas() {
        return this.pessoaexternas;
    }
    
    public void setPessoaexternas(Set pessoaexternas) {
        this.pessoaexternas = pessoaexternas;
    }




}


