package br.edu.unipampa.model;
// Generated 13/06/2014 19:43:05 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private Integer idPessoa;
     private String usuario;
     private String senha;
     private String email;
     private String nome;
     private String cpf;
     private String instituicao;
     private Set bancas = new HashSet(0);
     private Set alunos = new HashSet(0);
     private Set professors = new HashSet(0);

    public Pessoa() {
    }

	
    public Pessoa(String usuario, String senha, String email) {
        this.usuario = usuario;
        this.senha = senha;
        this.email = email;
    }
    public Pessoa(String usuario, String senha, String email, String nome, String cpf, String instituicao, Set bancas, Set alunos, Set professors) {
       this.usuario = usuario;
       this.senha = senha;
       this.email = email;
       this.nome = nome;
       this.cpf = cpf;
       this.instituicao = instituicao;
       this.bancas = bancas;
       this.alunos = alunos;
       this.professors = professors;
    }
   
    public Integer getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getInstituicao() {
        return this.instituicao;
    }
    
    public void setInstituicao(String instituicao) {
        this.instituicao = instituicao;
    }
    public Set getBancas() {
        return this.bancas;
    }
    
    public void setBancas(Set bancas) {
        this.bancas = bancas;
    }
    public Set getAlunos() {
        return this.alunos;
    }
    
    public void setAlunos(Set alunos) {
        this.alunos = alunos;
    }
    public Set getProfessors() {
        return this.professors;
    }
    
    public void setProfessors(Set professors) {
        this.professors = professors;
    }




}


