package br.edu.unipampa.model;
// Generated 12/06/2014 22:07:01 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Pessoaexterna generated by hbm2java
 */
public class Pessoaexterna  implements java.io.Serializable {


     private int idPessoaExterna;
     private Pessoa pessoa;
     private String nome;
     private String cpf;
     private String instituicao;
     private Set bancas = new HashSet(0);

    public Pessoaexterna() {
    }

	
    public Pessoaexterna(int idPessoaExterna, Pessoa pessoa) {
        this.idPessoaExterna = idPessoaExterna;
        this.pessoa = pessoa;
    }
    public Pessoaexterna(int idPessoaExterna, Pessoa pessoa, String nome, String cpf, String instituicao, Set bancas) {
       this.idPessoaExterna = idPessoaExterna;
       this.pessoa = pessoa;
       this.nome = nome;
       this.cpf = cpf;
       this.instituicao = instituicao;
       this.bancas = bancas;
    }
   
    public int getIdPessoaExterna() {
        return this.idPessoaExterna;
    }
    
    public void setIdPessoaExterna(int idPessoaExterna) {
        this.idPessoaExterna = idPessoaExterna;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getInstituicao() {
        return this.instituicao;
    }
    
    public void setInstituicao(String instituicao) {
        this.instituicao = instituicao;
    }
    public Set getBancas() {
        return this.bancas;
    }
    
    public void setBancas(Set bancas) {
        this.bancas = bancas;
    }

    public String getSenha(){
        return pessoa.getSenha();
    }

    public String getUsuario(){
        return pessoa.getUsuario();
    }
}


