package br.edu.unipampa.model;
// Generated 16/07/2014 21:01:23 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Professor generated by hbm2java
 */
public class Professor extends Pessoa implements java.io.Serializable {

    private int siape;
    private Pessoa pessoa;
    private Set orientadors = new HashSet(0);

    public Professor() {
    }

    public Professor(int siape, Pessoa pessoa) {
        this.siape = siape;
        this.pessoa = pessoa;
    }

    public Professor(int siape, Pessoa pessoa, Set orientadors) {
        this.siape = siape;
        this.pessoa = pessoa;
        this.orientadors = orientadors;
    }

    public int getSiape() {
        return this.siape;
    }

    public void setSiape(int siape) {
        this.siape = siape;
    }

    public Pessoa getPessoa() {
        return this.pessoa;
    }

    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    public Set getOrientadors() {
        return this.orientadors;
    }

    public void setOrientadors(Set orientadors) {
        this.orientadors = orientadors;
    }

    @Override
    public String getSenha() {
        return pessoa.getSenha();
    }

    @Override
    public String getNome() {
        return pessoa.getNome();
    }

    @Override
    public String getUsuario() {
        return pessoa.getUsuario();
    }
    
    @Override
    public String getEmail() {
        return pessoa.getEmail();
    }
    
    @Override
    public Integer getIdPessoa() {
        return pessoa.getIdPessoa();
    }

}
