package br.edu.unipampa.model;
// Generated 13/06/2014 19:43:05 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Professor generated by hbm2java
 */
public class Professor  implements java.io.Serializable {


     private int siape;
     private Pessoa pessoa;
     private Set bancas = new HashSet(0);
     private Set temas = new HashSet(0);

    public Professor() {
    }

	
    public Professor(int siape, Pessoa pessoa) {
        this.siape = siape;
        this.pessoa = pessoa;
    }
    public Professor(int siape, Pessoa pessoa, Set bancas, Set temas) {
       this.siape = siape;
       this.pessoa = pessoa;
       this.bancas = bancas;
       this.temas = temas;
    }
   
    public int getSiape() {
        return this.siape;
    }
    
    public void setSiape(int siape) {
        this.siape = siape;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Set getBancas() {
        return this.bancas;
    }
    
    public void setBancas(Set bancas) {
        this.bancas = bancas;
    }
    public Set getTemas() {
        return this.temas;
    }
    
    public void setTemas(Set temas) {
        this.temas = temas;
    }

    public String getSenha(){
        return pessoa.getSenha();
    }
    
    public String getUsuario(){
        return pessoa.getUsuario();
    }
    
}


