package br.edu.unipampa.model;
// Generated 16/07/2014 21:01:23 by Hibernate Tools 3.6.0



/**
 * Tecnicoadministrativo generated by hbm2java
 */
public class Tecnicoadministrativo  implements java.io.Serializable {


     private Integer idTecnicoAdministrativo;
     private Pessoa pessoa;

    public Tecnicoadministrativo() {
    }

    public Tecnicoadministrativo(Pessoa pessoa) {
       this.pessoa = pessoa;
    }
   
    public Integer getIdTecnicoAdministrativo() {
        return this.idTecnicoAdministrativo;
    }
    
    public void setIdTecnicoAdministrativo(Integer idTecnicoAdministrativo) {
        this.idTecnicoAdministrativo = idTecnicoAdministrativo;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }




}


