package br.edu.unipampa.model;
// Generated 02/07/2014 01:11:04 by Hibernate Tools 3.6.0

/**
 * Tema generated by hbm2java
 */
public class Tema implements java.io.Serializable {
    
    public static final int APROVADO_ORIENTADOR = 1;//Se o tema foi aprovado pelo orientador
    public static final int APROVADO_COODENADOR = 2;//Se o tema foi aprovado pelo coordenador
    public static final int NAO_APROVADO = 0;//Se o tema ainda não foi aprovado
    
    private Integer idTema;
    private Professor professor;
    private Aluno aluno;
    private Integer aprovado;
    private String descricao;

    public Tema() {
    }

    public Tema(Professor professor, Aluno aluno) {
        this.professor = professor;
        this.aluno = aluno;
    }

    public Tema(Professor professor, Aluno aluno, Integer aprovado, String descricao) {
        this.professor = professor;
        this.aluno = aluno;
        this.aprovado = aprovado;
        this.descricao = descricao;
    }

    public Integer getIdTema() {
        return this.idTema;
    }

    public void setIdTema(Integer idTema) {
        this.idTema = idTema;
    }

    public Professor getProfessor() {
        return this.professor;
    }

    public void setProfessor(Professor professor) {
        this.professor = professor;
    }

    public Aluno getAluno() {
        return this.aluno;
    }

    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }

    public Integer getAprovado() {
        return this.aprovado;
    }

    public void setAprovado(Integer aprovado) {
        this.aprovado = aprovado;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

}
