package br.edu.unipampa.bancoDeDados.classes;
// Generated 03/06/2014 11:00:57 by Hibernate Tools 3.6.0



/**
 * Banca generated by hbm2java
 */
public class Banca  implements java.io.Serializable {


     private int professorSiape;
     private Professor professor;
     private Aluno aluno;
     private Pessoa pessoa;

    public Banca() {
    }

    public Banca(Professor professor, Aluno aluno, Pessoa pessoa) {
       this.professor = professor;
       this.aluno = aluno;
       this.pessoa = pessoa;
    }
   
    public int getProfessorSiape() {
        return this.professorSiape;
    }
    
    public void setProfessorSiape(int professorSiape) {
        this.professorSiape = professorSiape;
    }
    public Professor getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Professor professor) {
        this.professor = professor;
    }
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }




}


