package br.edu.unipampa.bancoDeDados.classes;
// Generated 03/06/2014 11:00:57 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Professor generated by hbm2java
 */
public class Professor  implements java.io.Serializable {


     private int siape;
     private Pessoa pessoa;
     private Banca banca;
     private Set temas = new HashSet(0);

    public Professor() {
    }

	
    public Professor(int siape, Pessoa pessoa) {
        this.siape = siape;
        this.pessoa = pessoa;
    }
    public Professor(int siape, Pessoa pessoa, Banca banca, Set temas) {
       this.siape = siape;
       this.pessoa = pessoa;
       this.banca = banca;
       this.temas = temas;
    }
   
    public int getSiape() {
        return this.siape;
    }
    
    public void setSiape(int siape) {
        this.siape = siape;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Banca getBanca() {
        return this.banca;
    }
    
    public void setBanca(Banca banca) {
        this.banca = banca;
    }
    public Set getTemas() {
        return this.temas;
    }
    
    public void setTemas(Set temas) {
        this.temas = temas;
    }

    public String getSenha(){
        return pessoa.getSenha();
    }


}


