package br.edu.unipampa.bancoDeDados.classes;
// Generated 03/06/2014 11:00:57 by Hibernate Tools 3.6.0



/**
 * TemaId generated by hbm2java
 */
public class TemaId  implements java.io.Serializable {


     private int professorSiape;
     private int alunoMatricula;

    public TemaId() {
    }

    public TemaId(int professorSiape, int alunoMatricula) {
       this.professorSiape = professorSiape;
       this.alunoMatricula = alunoMatricula;
    }
   
    public int getProfessorSiape() {
        return this.professorSiape;
    }
    
    public void setProfessorSiape(int professorSiape) {
        this.professorSiape = professorSiape;
    }
    public int getAlunoMatricula() {
        return this.alunoMatricula;
    }
    
    public void setAlunoMatricula(int alunoMatricula) {
        this.alunoMatricula = alunoMatricula;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TemaId) ) return false;
		 TemaId castOther = ( TemaId ) other; 
         
		 return (this.getProfessorSiape()==castOther.getProfessorSiape())
 && (this.getAlunoMatricula()==castOther.getAlunoMatricula());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProfessorSiape();
         result = 37 * result + this.getAlunoMatricula();
         return result;
   }   


}


